apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flexiroaster-backend-hpa
  namespace: flexiroaster
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flexiroaster-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flexiroaster-worker-hpa
  namespace: flexiroaster
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flexiroaster-worker
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
