apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - backend.yaml
  - frontend.yaml
  - worker.yaml
  - autoscaling.yaml
  - stage-execution-job.yaml
  - pipeline-scheduler-cronjob.yaml
